version: '3'
services:

 docker-tutorial:
  build:
    context: .
    dockerfile: Dockerfile
  image: php-alone
  ports:
    - "8080:80"
  volumes:
    - .:/var/www/html
  links:
   - mysql
  environment:
      DB_HOST: mysql
      DB_DATABASE: docker
      DB_USERNAME: docker
      DB_PASSWORD: docker

 mysql:
  image: mysql:5.7
  ports:
    - 3306:3306
  environment:
   MYSQL_DATABASE: docker
   MYSQL_USER: docker
   MYSQL_PASSWORD: docker
   MYSQL_ROOT_PASSWORD: docker

 phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  links:
  - mysql
  ports:
  - "8081:80"
  environment:
   PMA_HOST: mysql
